spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/tiendavirtual
    username: root
    password: ""
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.r2dbc: DEBUG
